# Synthwave84 Terminal Color Scheme
# Compatible with terminals that support TOML configuration

[colors]
# Core colors
background = "#241b2f"
foreground = "#ffffff"
cursor = "#ff7edb"
cursor_text = "#241b2f"
selection_background = "#ff7edb40"
selection_foreground = "#ffffff"

# Normal colors
[colors.normal]
black = "#241b2f"
red = "#fe4450"
green = "#72f1b8"
yellow = "#fede5d" 
blue = "#03edf9"
magenta = "#ff7edb"
cyan = "#36f9f6"
white = "#ffffff"

# Bright colors
[colors.bright]
black = "#495495"
red = "#fe4450"
green = "#72f1b8"
yellow = "#fede5d"
blue = "#03edf9"
magenta = "#ff7edb"
cyan = "#36f9f6"
white = "#ffffff"

# Dim colors (for reduced intensity)
[colors.dim]
black = "#241b2f"
red = "#fe445080"
green = "#72f1b880"
yellow = "#fede5d80"
blue = "#03edf980"
magenta = "#ff7edb80"
cyan = "#36f9f680"
white = "#ffffff80"